// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http-server/handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/http-server/handlers.go -destination=mocks/service.go
//

// Package mock_server is a generated GoMock package.
package mock_server

import (
	model "avito/internal/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateBanner mocks base method.
func (m *MockServiceInterface) CreateBanner(ctx context.Context, banner model.BannerCreate) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBanner", ctx, banner)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBanner indicates an expected call of CreateBanner.
func (mr *MockServiceInterfaceMockRecorder) CreateBanner(ctx, banner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBanner", reflect.TypeOf((*MockServiceInterface)(nil).CreateBanner), ctx, banner)
}

// DeleteBanner mocks base method.
func (m *MockServiceInterface) DeleteBanner() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteBanner")
}

// DeleteBanner indicates an expected call of DeleteBanner.
func (mr *MockServiceInterfaceMockRecorder) DeleteBanner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBanner", reflect.TypeOf((*MockServiceInterface)(nil).DeleteBanner))
}

// GetBanners mocks base method.
func (m *MockServiceInterface) GetBanners(ctx context.Context, bannersFilters model.BannersFilter) ([]model.BannerCreate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBanners", ctx, bannersFilters)
	ret0, _ := ret[0].([]model.BannerCreate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBanners indicates an expected call of GetBanners.
func (mr *MockServiceInterfaceMockRecorder) GetBanners(ctx, bannersFilters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBanners", reflect.TypeOf((*MockServiceInterface)(nil).GetBanners), ctx, bannersFilters)
}

// GetUserBanner mocks base method.
func (m *MockServiceInterface) GetUserBanner(ctx context.Context, bannersFilters model.BannersFilter) ([]model.BannerCreate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBanner", ctx, bannersFilters)
	ret0, _ := ret[0].([]model.BannerCreate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBanner indicates an expected call of GetUserBanner.
func (mr *MockServiceInterfaceMockRecorder) GetUserBanner(ctx, bannersFilters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBanner", reflect.TypeOf((*MockServiceInterface)(nil).GetUserBanner), ctx, bannersFilters)
}

// UpdateBanner mocks base method.
func (m *MockServiceInterface) UpdateBanner(ctx context.Context, banner model.BannerUpdateRequest) (model.BannerCreate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBanner", ctx, banner)
	ret0, _ := ret[0].(model.BannerCreate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBanner indicates an expected call of UpdateBanner.
func (mr *MockServiceInterfaceMockRecorder) UpdateBanner(ctx, banner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBanner", reflect.TypeOf((*MockServiceInterface)(nil).UpdateBanner), ctx, banner)
}
